### ISSUE TITLE
no changelog found for xo

### ISSUE THREAD

**Issue by OmgImAlexis** [th0r/npm-upgrade#46]
```shell
? Update "xo" in package.json from ^0.29.0 to ^0.30.0? Show changelog
Trying to find changelog URL...
Sorry, we haven't found any changelog URL for xo module.
It would be great if you could fill an issue about this here: https://github.com/th0r/npm-upgrade/issues
Thanks a lot!
```

https://github.com/xojs/xo

**Comment by RiZKiT** [comment]
The [repository entry in the related package.json](https://github.com/xojs/xo/blob/master/package.json#L6) has very few informations, it's just a relative path without any information about github. 

I see two options here, file an issue there about this or handle relative paths here.

[The official repository definition](https://docs.npmjs.com/files/package.json#repository) allows relative paths for "GitHub, GitHub gist, Bitbucket or GitLab repositories", so I expect it should be fixed in npm-upgrade.

**Comment by th0r** [comment]
It works for me:
```
$ npm-upgrade changelog xo
Trying to find changelog URL for xo...
Opening https://github.com/xojs/xo/releases...
```
Looks like either you had some network problems or Github was unavailable at the time you tried that.

**Comment by OmgImAlexis** [comment]
That wasn’t the case. It’s happened every single time I’ve tried this. Doubt I’ve had issues every time.

**Comment by th0r** [comment]
But what about now?
