### ISSUE TITLE
Add feature to postprone module updates

### ISSUE THREAD

**Issue by th0r** [th0r/npm-upgrade#7]
It will help a lot when you want to postprone updating of some modules and not to answer `N` every time you run `npm-upgrade`.

**Comment by vjpr** [comment]
+1 This would help a lot. Perhaps adding an 'npm-upgrade' key to the `package.json` with the packages to ignore.

It might also be useful to specify certain modules to abide by semver. I prefer being able to check which modules will be updated using `npm-upgrade` rather than running `npm update`. Not sure the best way to store this info in a non-confusing way...

**Comment by th0r** [comment]
Yes, the question is where to store these postproned modules list.
I wonder whether this file should be stored in the current project's directory or it's better to create one file for all the projects in the current user's home directory and store this data using project directory as a key?
The question is whether it's a project's or user's data...

**Comment by vjpr** [comment]
It's definitely project-specific for me.

**Comment by slmgc** [comment]
@th0r do you have any updates on this feature?

**Comment by th0r** [comment]
@slmgc Yes, I started it but don't have time right now. Will do it ASAP.

**Comment by th0r** [comment]
Added in `v1.0.1`
